#LIST:
mylist1=['a',10,7.2,'John']
print(mylist1[0])
print(mylist1[1])
print(mylist1[3])
#concatenation
mylist2=['python',20]
mylist1+=mylist2
print(mylist1)
#Repitiions
print(mylist2*2)
#Slicing
print(mylist1[1:5])
#Append
mylist2.append("10")
print(mylist2)
#Extend
l=['c','d']
mylist2.extend(l)
print(mylist2)
#Insert
l.insert(1,30)
print(l)
#Remove
l.remove('d')
print(l)
mylist1.remove(7.2)
print(mylist1)
#Length
print(l)
print(mylist1)
print(mylist2)
